---------------------------------------
Begin Slurm Prolog: Apr-09-2024 22:46:49
Job ID:    5609545
User ID:   cchen847
Account:   gts-rs275
Job name:  nerf2_test
Partition: gpu-a100
QOS:       inferno
---------------------------------------
Defaulting to user installation because normal site-packages is not writeable
Collecting scipy==1.10.0
  Downloading scipy-1.10.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scipy==1.10.0) (1.21.5)
Installing collected packages: scipy
Successfully installed scipy-1.10.0
Defaulting to user installation because normal site-packages is not writeable
Collecting mne==1.6.1
  Downloading mne-1.6.1-py3-none-any.whl (8.3 MB)
Collecting pooch>=1.5
  Downloading pooch-1.8.1-py3-none-any.whl (62 kB)
Requirement already satisfied: tqdm in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (4.64.0)
Requirement already satisfied: jinja2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (2.11.3)
Requirement already satisfied: numpy>=1.21.2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (1.21.5)
Requirement already satisfied: matplotlib>=3.5.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (3.5.1)
Requirement already satisfied: decorator in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (5.1.1)
Requirement already satisfied: packaging in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne==1.6.1) (21.3)
Collecting lazy-loader>=0.3
  Downloading lazy_loader-0.4-py3-none-any.whl (12 kB)
Requirement already satisfied: scipy>=1.7.1 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne==1.6.1) (1.10.0)
Requirement already satisfied: cycler>=0.10 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (9.0.1)
Requirement already satisfied: fonttools>=4.22.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (4.25.0)
Requirement already satisfied: python-dateutil>=2.7 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (3.0.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne==1.6.1) (1.3.2)
Collecting platformdirs>=2.5.0
  Downloading platformdirs-4.2.0-py3-none-any.whl (17 kB)
Requirement already satisfied: requests>=2.19.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pooch>=1.5->mne==1.6.1) (2.27.1)
Requirement already satisfied: six>=1.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=3.5.0->mne==1.6.1) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne==1.6.1) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne==1.6.1) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne==1.6.1) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne==1.6.1) (1.26.9)
Requirement already satisfied: MarkupSafe>=0.23 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from jinja2->mne==1.6.1) (2.0.1)
Installing collected packages: platformdirs, pooch, lazy-loader, mne
  WARNING: The script mne is installed in '/storage/home/hcoda1/3/cchen847/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed lazy-loader-0.4 mne-1.6.1 platformdirs-4.2.0 pooch-1.8.1
Defaulting to user installation because normal site-packages is not writeable
Collecting mne_bids
  Downloading mne_bids-0.14-py2.py3-none-any.whl (1.2 MB)
Requirement already satisfied: scipy>=1.6.3 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne_bids) (1.10.0)
Requirement already satisfied: mne>=1.4 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne_bids) (1.6.1)
Requirement already satisfied: numpy>=1.20.2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne_bids) (1.21.5)
Requirement already satisfied: tqdm in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (4.64.0)
Requirement already satisfied: packaging in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (21.3)
Requirement already satisfied: jinja2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (2.11.3)
Requirement already satisfied: decorator in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (5.1.1)
Requirement already satisfied: pooch>=1.5 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (1.8.1)
Requirement already satisfied: lazy-loader>=0.3 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (0.4)
Requirement already satisfied: matplotlib>=3.5.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne>=1.4->mne_bids) (3.5.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (4.25.0)
Requirement already satisfied: pyparsing>=2.2.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (3.0.4)
Requirement already satisfied: python-dateutil>=2.7 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (9.0.1)
Requirement already satisfied: cycler>=0.10 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib>=3.5.0->mne>=1.4->mne_bids) (0.11.0)
Requirement already satisfied: requests>=2.19.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pooch>=1.5->mne>=1.4->mne_bids) (2.27.1)
Requirement already satisfied: platformdirs>=2.5.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pooch>=1.5->mne>=1.4->mne_bids) (4.2.0)
Requirement already satisfied: six>=1.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=3.5.0->mne>=1.4->mne_bids) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne>=1.4->mne_bids) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne>=1.4->mne_bids) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne>=1.4->mne_bids) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne>=1.4->mne_bids) (2021.10.8)
Requirement already satisfied: MarkupSafe>=0.23 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from jinja2->mne>=1.4->mne_bids) (2.0.1)
Installing collected packages: mne-bids
  WARNING: The script mne_bids is installed in '/storage/home/hcoda1/3/cchen847/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed mne-bids-0.14
Defaulting to user installation because normal site-packages is not writeable
Collecting pyriemann
  Downloading pyriemann-0.5.tar.gz (119 kB)
Requirement already satisfied: numpy!=1.24.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pyriemann) (1.21.5)
Requirement already satisfied: scipy in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pyriemann) (1.10.0)
Requirement already satisfied: scikit-learn in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pyriemann) (1.0.2)
Requirement already satisfied: joblib in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pyriemann) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scikit-learn->pyriemann) (2.2.0)
Building wheels for collected packages: pyriemann
  Building wheel for pyriemann (setup.py): started
  Building wheel for pyriemann (setup.py): finished with status 'done'
  Created wheel for pyriemann: filename=pyriemann-0.5-py2.py3-none-any.whl size=107755 sha256=fef9556b04b1521b58de51cde3ef86936af8a3e351bf8ff0504534c70390cff1
  Stored in directory: /storage/home/hcoda1/3/cchen847/.cache/pip/wheels/8a/80/19/94d7fa5fe77627f8576da984bca1b3ad3f4a6991e65273eba6
Successfully built pyriemann
Installing collected packages: pyriemann
Successfully installed pyriemann-0.5
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (1.0.2)
Requirement already satisfied: joblib>=0.11 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: scipy>=1.1.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from scikit-learn) (1.10.0)
Requirement already satisfied: numpy>=1.14.6 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scikit-learn) (1.21.5)
Defaulting to user installation because normal site-packages is not writeable
Collecting moabb
  Downloading moabb-1.0.0-py3-none-any.whl (563 kB)
Collecting numpy<2.0,>=1.22
  Downloading numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Collecting seaborn<0.13.0,>=0.12.1
  Downloading seaborn-0.12.2-py3-none-any.whl (293 kB)
Collecting pandas<2.0.0,>=1.5.2
  Downloading pandas-1.5.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
Collecting memory-profiler<0.62.0,>=0.61.0
  Downloading memory_profiler-0.61.0-py3-none-any.whl (31 kB)
Requirement already satisfied: PyYAML<7.0,>=6.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from moabb) (6.0)
Requirement already satisfied: pyriemann<0.6,>=0.5 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (0.5)
Collecting tqdm<5.0.0,>=4.64.1
  Downloading tqdm-4.66.2-py3-none-any.whl (78 kB)
Collecting edflib-python<2.0.0,>=1.0.6
  Downloading EDFlib_Python-1.0.8-py3-none-any.whl (26 kB)
Requirement already satisfied: h5py<=3.8.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from moabb) (3.6.0)
Requirement already satisfied: pooch<2.0.0,>=1.6.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (1.8.1)
Requirement already satisfied: scipy<2.0.0,>=1.9.3 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (1.10.0)
Collecting scikit-learn<2.0.0,>=1.2.0
  Downloading scikit_learn-1.4.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
Collecting urllib3<2.0.0,>=1.26.15
  Downloading urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
Collecting matplotlib<4.0.0,>=3.6.2
  Downloading matplotlib-3.8.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
Collecting coverage<8.0.0,>=7.0.1
  Downloading coverage-7.4.4-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (233 kB)
Collecting requests<3.0.0,>=2.28.1
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
Collecting pytest<8.0.0,>=7.4.0
  Downloading pytest-7.4.4-py3-none-any.whl (325 kB)
Collecting mne-bids<0.14,>=0.13
  Downloading mne_bids-0.13-py2.py3-none-any.whl (1.2 MB)
Requirement already satisfied: mne<2.0,>=1.4 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from moabb) (1.6.1)
Requirement already satisfied: python-dateutil>=2.7 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (2.8.2)
Requirement already satisfied: pyparsing>=2.3.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (3.0.4)
Requirement already satisfied: fonttools>=4.22.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (4.25.0)
Requirement already satisfied: cycler>=0.10 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (0.11.0)
Requirement already satisfied: pillow>=8 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (9.0.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (1.3.2)
Requirement already satisfied: packaging>=20.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from matplotlib<4.0.0,>=3.6.2->moabb) (21.3)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.2.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (304 kB)
Collecting importlib-resources>=3.2.0
  Downloading importlib_resources-6.4.0-py3-none-any.whl (38 kB)
Requirement already satisfied: zipp>=3.1.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib<4.0.0,>=3.6.2->moabb) (3.7.0)
Requirement already satisfied: psutil in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from memory-profiler<0.62.0,>=0.61.0->moabb) (5.8.0)
Requirement already satisfied: jinja2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne<2.0,>=1.4->moabb) (2.11.3)
Requirement already satisfied: decorator in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from mne<2.0,>=1.4->moabb) (5.1.1)
Requirement already satisfied: lazy-loader>=0.3 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from mne<2.0,>=1.4->moabb) (0.4)
Requirement already satisfied: pytz>=2020.1 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pandas<2.0.0,>=1.5.2->moabb) (2021.3)
Requirement already satisfied: platformdirs>=2.5.0 in /storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages (from pooch<2.0.0,>=1.6.0->moabb) (4.2.0)
Requirement already satisfied: joblib in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pyriemann<0.6,>=0.5->moabb) (1.1.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pytest<8.0.0,>=7.4.0->moabb) (1.0.0)
Requirement already satisfied: tomli>=1.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pytest<8.0.0,>=7.4.0->moabb) (1.2.2)
Requirement already satisfied: iniconfig in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from pytest<8.0.0,>=7.4.0->moabb) (1.1.1)
Collecting exceptiongroup>=1.0.0rc8
  Downloading exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
Requirement already satisfied: six>=1.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib<4.0.0,>=3.6.2->moabb) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests<3.0.0,>=2.28.1->moabb) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests<3.0.0,>=2.28.1->moabb) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from requests<3.0.0,>=2.28.1->moabb) (2021.10.8)
Requirement already satisfied: threadpoolctl>=2.0.0 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from scikit-learn<2.0.0,>=1.2.0->moabb) (2.2.0)
Collecting joblib
  Downloading joblib-1.4.0-py3-none-any.whl (301 kB)
Requirement already satisfied: MarkupSafe>=0.23 in /storage/pace-apps/manual/packages/anaconda3/2022.05.0.1/lib/python3.9/site-packages (from jinja2->mne<2.0,>=1.4->moabb) (2.0.1)
Installing collected packages: urllib3, numpy, requests, importlib-resources, contourpy, tqdm, matplotlib, joblib, scikit-learn, pandas, exceptiongroup, seaborn, pytest, mne-bids, memory-profiler, edflib-python, coverage, moabb
  WARNING: The script f2py is installed in '/storage/home/hcoda1/3/cchen847/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tqdm is installed in '/storage/home/hcoda1/3/cchen847/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts py.test and pytest are installed in '/storage/home/hcoda1/3/cchen847/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: mne-bids
    Found existing installation: mne-bids 0.14
    Uninstalling mne-bids-0.14:
      Successfully uninstalled mne-bids-0.14
  WARNING: The script mne_bids is installed in '/storage/home/hcoda1/3/cchen847/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mprof is installed in '/storage/home/hcoda1/3/cchen847/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts coverage, coverage-3.9 and coverage3 are installed in '/storage/home/hcoda1/3/cchen847/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.5.0 requires daal==2021.4.0, which is not installed.
conda-repo-cli 1.0.4 requires pathlib, which is not installed.
anaconda-project 0.10.2 requires ruamel-yaml, which is not installed.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.26.4 which is incompatible.
Successfully installed contourpy-1.2.1 coverage-7.4.4 edflib-python-1.0.8 exceptiongroup-1.2.0 importlib-resources-6.4.0 joblib-1.4.0 matplotlib-3.8.4 memory-profiler-0.61.0 mne-bids-0.13 moabb-1.0.0 numpy-1.26.4 pandas-1.5.3 pytest-7.4.4 requests-2.31.0 scikit-learn-1.4.2 seaborn-0.12.2 tqdm-4.66.2 urllib3-1.26.18
Processing raw data for subject 1
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Physionet_hands_feet_MI.py", line 201, in <module>
    read_raw_edf(f, preload=True) for f in eegbci.load_data(subject, sessions)
  File "<decorator-gen-315>", line 12, in load_data
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/eegbci/eegbci.py", line 181, in load_data
    path = _get_path(path, config_key, name)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 118, in _get_path
    raise FileNotFoundError(msg)
FileNotFoundError: Download location /storage/home/hcoda1/3/cchen847/mne_data as specified by MNE_DATA does not exist. Either create this directory manually and try again, or set MNE_DATA to an existing directory.
Processing raw data for subject 1
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Physionet_left_right_MI.py", line 201, in <module>
    read_raw_edf(f, preload=True) for f in eegbci.load_data(subject, sessions)
  File "<decorator-gen-315>", line 12, in load_data
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/eegbci/eegbci.py", line 181, in load_data
    path = _get_path(path, config_key, name)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 118, in _get_path
    raise FileNotFoundError(msg)
FileNotFoundError: Download location /storage/home/hcoda1/3/cchen847/mne_data as specified by MNE_DATA does not exist. Either create this directory manually and try again, or set MNE_DATA to an existing directory.
Processing raw data for subject 1
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Physionet_hands_feet_ME.py", line 201, in <module>
    read_raw_edf(f, preload=True) for f in eegbci.load_data(subject, sessions)
  File "<decorator-gen-315>", line 12, in load_data
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/eegbci/eegbci.py", line 181, in load_data
    path = _get_path(path, config_key, name)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 118, in _get_path
    raise FileNotFoundError(msg)
FileNotFoundError: Download location /storage/home/hcoda1/3/cchen847/mne_data as specified by MNE_DATA does not exist. Either create this directory manually and try again, or set MNE_DATA to an existing directory.
Processing raw data for subject 1
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Physionet_left_right_ME.py", line 201, in <module>
    read_raw_edf(f, preload=True) for f in eegbci.load_data(subject, sessions)
  File "<decorator-gen-315>", line 12, in load_data
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/eegbci/eegbci.py", line 181, in load_data
    path = _get_path(path, config_key, name)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 118, in _get_path
    raise FileNotFoundError(msg)
FileNotFoundError: Download location /storage/home/hcoda1/3/cchen847/mne_data as specified by MNE_DATA does not exist. Either create this directory manually and try again, or set MNE_DATA to an existing directory.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_types is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_channels_regexp is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.channel_type is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/pipelines/__init__.py:26: ModuleNotFoundError: Tensorflow is not installed. You won't be able to use these MOABB pipelines if you attempt to do so.
  warn(
To use the get_shape_from_baseconcar, InputShapeSetterEEG, BraindecodeDatasetLoaderyou need to install `braindecode`.`pip install braindecode` or Please refer to `https://braindecode.org`.
Loading subjects [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]...
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Shin2017A.py", line 208, in <module>
    data = dataset1.get_data(subjects=subjects, cache_config={'path': args.download_path})
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 342, in get_data
    data[subject] = self._get_single_subject_data_using_cache(
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 436, in _get_single_subject_data_using_cache
    sessions_data = self._get_single_subject_data(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bbci_eeg_fnirs.py", line 132, in _get_single_subject_data
    fname, fname_mrk = self.data_path(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bbci_eeg_fnirs.py", line 181, in data_path
    path = _get_path(path, key, "BBCI EEG-fNIRS")
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 118, in _get_path
    raise FileNotFoundError(msg)
FileNotFoundError: Download location /storage/home/hcoda1/3/cchen847/mne_data as specified by MNE_DATA does not exist. Either create this directory manually and try again, or set MNE_DATA to an existing directory.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_types is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_channels_regexp is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.channel_type is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/pipelines/__init__.py:26: ModuleNotFoundError: Tensorflow is not installed. You won't be able to use these MOABB pipelines if you attempt to do so.
  warn(
To use the get_shape_from_baseconcar, InputShapeSetterEEG, BraindecodeDatasetLoaderyou need to install `braindecode`.`pip install braindecode` or Please refer to `https://braindecode.org`.
Loading subjects [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]...
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Shin2017B.py", line 208, in <module>
    data = dataset1.get_data(subjects=subjects, cache_config={'path': args.download_path})
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 342, in get_data
    data[subject] = self._get_single_subject_data_using_cache(
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 436, in _get_single_subject_data_using_cache
    sessions_data = self._get_single_subject_data(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bbci_eeg_fnirs.py", line 132, in _get_single_subject_data
    fname, fname_mrk = self.data_path(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bbci_eeg_fnirs.py", line 181, in data_path
    path = _get_path(path, key, "BBCI EEG-fNIRS")
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 118, in _get_path
    raise FileNotFoundError(msg)
FileNotFoundError: Download location /storage/home/hcoda1/3/cchen847/mne_data as specified by MNE_DATA does not exist. Either create this directory manually and try again, or set MNE_DATA to an existing directory.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_types is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_channels_regexp is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.channel_type is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/pipelines/__init__.py:26: ModuleNotFoundError: Tensorflow is not installed. You won't be able to use these MOABB pipelines if you attempt to do so.
  warn(
To use the get_shape_from_baseconcar, InputShapeSetterEEG, BraindecodeDatasetLoaderyou need to install `braindecode`.`pip install braindecode` or Please refer to `https://braindecode.org`.
Loading subjects [1, 2, 3, 4, 5, 6, 7, 8, 9]...
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_BNCI.py", line 208, in <module>
    data = dataset1.get_data(subjects=subjects, cache_config={'path': args.download_path})
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 342, in get_data
    data[subject] = self._get_single_subject_data_using_cache(
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 436, in _get_single_subject_data_using_cache
    sessions_data = self._get_single_subject_data(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bnci.py", line 738, in _get_single_subject_data
    sessions = load_data(subject=subject, dataset=self.code, verbose=False)
  File "<decorator-gen-435>", line 10, in load_data
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bnci.py", line 111, in load_data
    return dataset_list[dataset](
  File "<decorator-gen-443>", line 10, in _load_data_004_2015
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bnci.py", line 411, in _load_data_004_2015
    filename = data_path(url, path, force_update, update_path)[0]
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bnci.py", line 20, in data_path
    return [dl.data_dl(url, "BNCI", path, force_update, verbose)]
  File "<decorator-gen-434>", line 12, in data_dl
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/download.py", line 136, in data_dl
    path = Path(get_dataset_path(sign, path))
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/download.py", line 56, in get_dataset_path
    return _get_path(path, key, sign)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 118, in _get_path
    raise FileNotFoundError(msg)
FileNotFoundError: Download location /storage/home/hcoda1/3/cchen847/mne_data as specified by MNE_DATA does not exist. Either create this directory manually and try again, or set MNE_DATA to an existing directory.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_types is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.pick_channels_regexp is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
<frozen importlib._bootstrap>:228: FutureWarning: mne.io.pick.channel_type is deprecated will be removed in 1.6, use documented public API instead. If no appropriate public API exists, please open an issue on GitHub.
/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/pipelines/__init__.py:26: ModuleNotFoundError: Tensorflow is not installed. You won't be able to use these MOABB pipelines if you attempt to do so.
  warn(
To use the get_shape_from_baseconcar, InputShapeSetterEEG, BraindecodeDatasetLoaderyou need to install `braindecode`.`pip install braindecode` or Please refer to `https://braindecode.org`.
Loading subjects [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]...
Traceback (most recent call last):
  File "/storage/coda1/p-rs275/0/cchen847/da_eeg/mDA/Notebook/mDA_Schirrmeister.py", line 210, in <module>
    data = dataset1.get_data(subjects=subjects)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 342, in get_data
    data[subject] = self._get_single_subject_data_using_cache(
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/base.py", line 436, in _get_single_subject_data_using_cache
    sessions_data = self._get_single_subject_data(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bbci_eeg_fnirs.py", line 132, in _get_single_subject_data
    fname, fname_mrk = self.data_path(subject)
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/moabb/datasets/bbci_eeg_fnirs.py", line 181, in data_path
    path = _get_path(path, key, "BBCI EEG-fNIRS")
  File "/storage/home/hcoda1/3/cchen847/.local/lib/python3.9/site-packages/mne/datasets/utils.py", line 118, in _get_path
    raise FileNotFoundError(msg)
FileNotFoundError: Download location /storage/home/hcoda1/3/cchen847/mne_data as specified by MNE_DATA does not exist. Either create this directory manually and try again, or set MNE_DATA to an existing directory.
---------------------------------------
Begin Slurm Epilog: Apr-09-2024 22:49:03
Job ID:        5609545
Array Job ID:  _4294967294
User ID:       cchen847
Account:       gts-rs275
Job name:      nerf2_test
Resources:     cpu=8,gres/gpu:a100=1,mem=10G,node=1
Rsrc Used:     cput=00:17:52,vmem=550396K,walltime=00:02:14,mem=99844K,energy_used=0
Partition:     gpu-a100
QOS:           inferno
Nodes:         atl1-1-02-018-29-0
---------------------------------------
